#default setting
server:
  port: 10009
spring:
  application:
    name: munzi-log
  profiles:
    group:
      local: local-munzi-log
      dev: dev-munzi-log
      prod: prod-munzi-log
    active: local
  jackson:
    serialization:
      write_dates_as_timestamps: true
  output:
    ansi:
      enabled: ALWAYS


---

spring:
  config:
    activate:
      on-profile: local-munzi-log

#logging:
#  config: classpath:log4j2-local.yml

---

spring:
  config:
    activate:
      on-profile: dev-munzi-log

#logging:
#  config: classpath:log4j2-dev.yml
---

spring:
  config:
    activate:
      on-profile: prod-munzi-log

#logging:
#  config: classpath:log4j2-prod.yml
