app:
  name: munzi-log
  version: 1.0.0
server:
  port: 10009
spring:
  application:
    name: munzi-log
  profiles:
    group:
      local: local-munzi-log
      dev: dev-munzi-log
      prod: prod-munzi-log
    active: local
  jackson:
    serialization:
      write_dates_as_timestamps: true
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/~/totoro
    username: sa
    password:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100

custom:
  log-filter:
    use: true # filter 전체 사용 여부
    request:
      max-body-size: 1KB # request body max size
      secret: # 해당 api의 경우, body 전체를 로그에 안찍음
        api: POST /hello/secret
    response:
      max-body-size: 1bytes # response body max size
      secret: # 해당 api의 경우, body 전체를 로그에 안찍음
        api: GET /hello/secret

---

spring:
  config:
    activate:
      on-profile: local-munzi-log

logging:
  config: file:/Users/hjpark/Documents/dkargo/logging-module/munzi-log/config/log4j2-local.yml

---

spring:
  config:
    activate:
      on-profile: dev-munzi-log

logging:
  config: file:/Users/hjpark/Documents/dkargo/logging-module/munzi-log/config/log4j2-dev.yml
---

spring:
  config:
    activate:
      on-profile: prod-munzi-log

logging:
  config: file:/Users/hjpark/Documents/dkargo/logging-module/munzi-log/config/log4j2-prod.yml
