## ---------- personal custom setting
#custom:
#  logging:
#    path: /apps/logs/munzi-log
#    filename: a.log
#    level:
#      default: INFO
##    format: "%clr(%-5level) %clr(%date){cyan} %clr(%thread){yellow} %clr([%logger{36}.%M:%line]){blue} %msg%n"
#    format: "%highlight{[%-5p]}{FATAL=bg_red, ERROR=red, INFO=green, DEBUG=blue} %style{%d{yyyy/MM/dd HH:mm:ss,SSS}}{cyan} [%C] %style{[%t]}{yellow}- %m%n"

## ---------- logging
##logging.config: classpath:logback-${spring.profiles.active}.xml
#logging:
#  # level
#  level:
#    # default
#    root: ${custom.logging.level.default}
#    # packages
#    com.withwiz: INFO
#    com.withwiz.cryptocurrency: INFO
#    # spring
#    org.springframework.web: ERROR
#    # hibernate
#    org.hibernate: ERROR
#    org.hibernate.SQL: DEBUG
#    #org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#    # log4jdbc
#    jdbc: OFF
#    # for connection "open" or "close"
#    jdbc.connection: ERROR
#    # for sql
#    jdbc.sqlonly: DEBUG
#    # for query time(milliseconds)
#    jdbc.sqltiming: OFF
#    # alls except for resultset
#    jdbc.audit: OFF
#    # with resultset
#    jdbc.resultset: OFF
#    # with resultset table
#    jdbc.resultsettable: DEBUG
#    # hikari
#    com.zaxxer.hikari.HikariDataSource: ERROR
#    # howtodoinjava
#    com.howtodoinjav: INFO
#  file:
#    # log file full path
#    name: ${custom.logging.path}/${custom.logging.filename}
#    # max history(days)
#    max-history: 30
#    # max size per file
#    max-size: 500MB
#  # log formatter
#  pattern:
#    console: ${custom.logging.format}
#    file: ${custom.logging.format}


spring.output:
    ansi:
      enabled: ALWAYS


#default setting
server:
  port: 10009
spring:
  application:
    name: munzi-log
  profiles:
    group:
      local: local-munzi-log
      dev: dev-munzi-log
      prod: prod-munzi-log
    active: local
  jackson:
    serialization:
      write_dates_as_timestamps: true

---

spring:
  config:
    activate:
      on-profile: local-munzi-log

logging:
  config: file:/Users/uni4love/project/workspace/deleo/git-repo/logging-module/munzi-log/config/log4j2.yml

---

spring:
  config:
    activate:
      on-profile: dev-munzi-log

#logging:
#  config: classpath:log4j2-dev.yml
---

spring:
  config:
    activate:
      on-profile: prod-munzi-log

#logging:
#  config: classpath:log4j2-prod.yml
