Configuration:
  name: log4j2 dev
  status: DEBUG
  monitorInterval: 30

  Properties:
    Property:
      - name: log-path
        value: "/apps/logs/munzi-log"
      - name: log-filename
        value: "munzi-log.log"
      - name: log-pattern
        value: "%highlight{[%-5p]}{FATAL=bg_red, ERROR=red, INFO=green, DEBUG=blue} %style{%d{yyyy/MM/dd HH:mm:ss.SSS}}{cyan} %style{[%t:%tp]}{yellow} %style{[%C{1.}.%M:%L]}{blue} %m%n"

  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: ${log-pattern}
    RollingFile:
      name: RollingFile_Appender
      fileName: ${log-path}/${log-filename}
      filePattern: ${log-path}/archive/${log-filename}.%d{yyyy-MM-dd-hh-mm}.gz
      PatternLayout:
        pattern: ${log-pattern}
      Policies:
        SizeBasedTriggeringPolicy:
          size: 500 MB
      DefaultRollOverStrategy:
        max: 30
        Delete:
          basePath: ${log-path}/archive
          maxDepth: 1
          IfAccumulatedFileCount:
            exceeds: 31

  Loggers:
    Root:
      level: INFO
      AppenderRef:
        - ref: Console_Appender
        - ref: RollingFile_Appender
    Logger:
      - name: log.munzi
        additivity: false
        level: DEBUG
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender
      - name: org.springframework.web
        additivity: false
        level: ERROR
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender
      - name: org.springframework.web.filter
        additivity: false
        level: DEBUG
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender
      - name: org.hibernate
        additivity: false
        level: ERROR
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender
      - name: org.hibernate.SQL
        additivity: false
        level: DEBUG
        AppenderRef:
          - ref: Console_Appender
          - ref: RollingFile_Appender